sudo: false
language: node_js
branches:
  only:
  - master
node_js:
  - 6
script:
  - npm run build -s
  - npm run deploy -s -- --token=$NOW_TOKEN
  - npm run alias -s -- --token=$NOW_TOKEN
  - npm run cleanup -s -- iamstarkov.com --token=$NOW_TOKEN --yes
