sudo: false
language: node_js
branches:
  only:
  - premaster
node_js:
  - 7
script:
  - git config --global user.email "gh-pages@localhost"
  - git config --global user.name "npm gh-pages"
  - npm run deploy:ci -s
