sudo: false
language: node_js
branches:
  only:
  - premaster
  - /^greenkeeper/.*$/
node_js:
- 'stable'
before_script:
- git config --global user.email "noreply@localhost"
- git config --global user.name "noreply"
- npm run deploy:ci
