sudo: false
language: node_js
branches:
  only:
  - master
node_js:
  - 6
script:
  - npm run build
  - npm run deploy -- --token=$NOW_TOKEN
  - npm run alias -- --token=$NOW_TOKEN
  - npm run cleanup -- --token=$NOW_TOKEN
